math: mathjax
paginate: true
author: R. Johnson
style: |
  section.objectives > ol > li {
      list-style-type: lower-alpha;
  }

  section.columns, ol {
    display: block;
    column-count: 2;
  }

  section.columns > h1,h2 {
    column-span: all;
  }