allowLocalFiles: true
author: Russell Johnson
bespoke:
  osc: true
  progress: true
  transition: true
html: true
image: false
images: false
inputDir: "./src copy"
output: ./public
pdf: false
themeSet: ./themes/
theme: uncover
