allowLocalFiles: true
author: Russell Johnson
inlineSvg: true
bespoke:
  osc: true
  transition: true
html: true
image: false
images: false
pdf: false
themeSet: themes
indexFileTheme: gaia
sourceDirectory: test
destinationDirectory: dist
